### ISSUE TITLE
No such file

### ISSUE THREAD

**Issue by Laugelk18** [victorman/ArduinoMetronome#1]
When i try to upload the file to my Arduino board, i get the message "pitches.h: No such file or directory". What should i do!?

**Comment by victorman** [comment]
I will look into this as soon as I have an opportunity. In the meantime can you verify what is in the directory with the metronome.iso file?

For a quick fix:
you only need the constants NOTE_C4 and NOTE_C6 from that header file so you can simply copy
```
#define NOTE_C4 262
#define NOTE_C6 1047
```
to line 4 of metronome.ino and **delete** line 3 (the line that says '#include "pitches.h"')

After that edit, the first 3 lines of metronome.ino would be this:
```
#include <LiquidCrystal.h>
#define NOTE_C4 262
#define NOTE_C6 1047
```
